import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :one_playlist, OnePlaylistWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :one_playlist, OnePlaylistWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Bond contract checking in production.
#
# Preconditions are fully on: they are the cheapest kind and the only one that
# names a *caller's* bug, which is exactly the failure you cannot reconstruct
# from the callee's logs afterwards.
#
# The rest are `false` rather than `:purge`. Both leave them inert, but `:purge`
# removes the code entirely, and `false` compiles it in and gates it on a single
# lock-free `:persistent_term` read per kind per call. That gate is the whole
# point: it buys the ability to turn postconditions on from a remote console
# while an incident is in progress —
#
#     Bond.Config.enable(:postconditions)
#
# — and off again, without a deploy. A purged build offers nothing to enable.
#
# Two consequences worth knowing:
#
#   * An assertion must be *sound*, not merely inert. "It is off in production"
#     is not a licence to write one that could accuse correct code, because
#     anyone can switch it on. That is why the racing table-count postcondition
#     on `disconnect/2` was deleted rather than left disabled.
#   * Nothing here is purged, so `import Bond.Predicates` used only inside an
#     assertion stays used, and a release does not warn about it.
config :bond,
  preconditions: true,
  postconditions: false,
  invariants: false,
  checks: false
